import { Mail, ShieldCheck, Wrench } from 'lucide-react'
import { PRODUCT_NAME, SUPPORT_EMAIL } from '../app/config'
import seoMetadata from '../app/seo.json'
import { Seo } from '../components/common/Seo'

const content = {
  about: { title: `About ${PRODUCT_NAME}`, description: 'Private, practical browser-based tools for everyday development work.', icon: Wrench, body: <><p>{PRODUCT_NAME} is a focused set of browser-based tools for formatting, validating, and reviewing structured text without sending the document to a server.</p><h2>Built for Developers</h2><p>Work quickly with JSON, YAML, XML, SQL, and Markdown using clear controls, useful validation feedback, and familiar file, copy, and download actions.</p><h2>Privacy by Design</h2><p>Your documents are processed in the browser. Site measurements never include editor contents, uploaded files, filenames, queries, or tokens.</p><h2>Simple and Accessible</h2><p>The interface is responsive, keyboard-friendly, and intentionally consistent across tools, so the work stays in focus on desktop and mobile.</p></> },
  privacy: { title: 'Privacy', description: 'How DevMaster Tools keeps your documents private.', icon: ShieldCheck, body: <><p>{PRODUCT_NAME} is designed so your work stays private. Documents are processed locally in your browser, without an account or document backend.</p><h2>Your content stays on your device</h2><p>Editor contents, uploaded files and filenames, formatted output, validation details, tokens, and SQL queries are never sent to us, analytics providers, or any other third party.</p><p>The site records limited, anonymous usage and performance measurements. These measurements contain no document content or other text you provide. Analytics storage, advertising storage, personalization, and advertising signals remain disabled.</p><h2>What is saved</h2><p>A manual light or dark theme choice may be saved in local storage. {PRODUCT_NAME} does not save your documents in local storage, session storage, IndexedDB, or cookies. Downloaded files are handled by your browser.</p></> },
  contact: { title: 'Get in Touch', description: 'Contact DevMaster Tools support or report an issue.', icon: Mail, body: <><p>Have a question, suggestion, or issue with {PRODUCT_NAME}? Email <a className="text-link" href={`mailto:${SUPPORT_EMAIL}`}>{SUPPORT_EMAIL}</a>.</p><p><a className="primary-button contact-button" href={`mailto:${SUPPORT_EMAIL}?subject=${encodeURIComponent('DevMaster Tools Support')}`}>Contact Support</a></p><h2>Before reporting a formatting issue</h2><p>Include the tool, selected formatting options, browser version, and a minimal non-sensitive example when possible. Never send secrets, access tokens, production credentials, or private documents.</p></> },
}

export function InfoPage({ page }: { page: keyof typeof content }) {
  const item = content[page]
  return <main className="info-page"><Seo title={seoMetadata.pages[page].title} description={seoMetadata.pages[page].description} path={seoMetadata.pages[page].path} /><div className="info-icon"><item.icon /></div><p className="eyebrow">{PRODUCT_NAME}</p><h1>{item.title}</h1><div className="info-copy">{item.body}</div></main>
}
